sample_packets:
- description: OTAA Join Request (valid MIC, LSB format)
  hex: 00887766554433221108070605040302011234F20B8567
- description: Physical payload (MAC Layer only)
  hex: 400403020100010148656C6C6FAABBCCDD


##############   GW and NS connection ###########

GATEWAY_IP: "192.168.1.50"   # Pi’s IP (or "127.0.0.1" for local tests)
SERVER_IP: "0.0.0.0"         # Listen on all interfaces on the server
UDP_PORT: 1700
BUF_SIZE: 8192
